<a href="https://colab.research.google.com/github/swasfish-code/python/blob/main/IITH_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

students = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": [
        "Rahul", "Priya", "Amit", "Sneha", "Rohan",
        "Neha", "Arjun", "Pooja", "Karan", "Meera"
    ],
    "Branch": [
        "CSE", "ECE", "CSE", "IT", "CSE",
        "ECE", "IT", "CSE", "ECE", "IT"
    ],
    "Marks": [85, 78, 92, 67, 88, 76, 95, 81, 72, 89],
    "Attendance": [92, 85, 78, 65, 90, 88, 96, 72, 80, 94],
    "Study_Hours": [5, 4, 7, 2, 6, 4, 8, 5, 3, 6],
    "Placement_Training": [
        "Yes", "No", "Yes", "No", "Yes",
        "Yes", "Yes", "No", "No", "Yes"
    ]
})

students

   Student_ID   Name Branch  Marks  Attendance  Study_Hours Placement_Training
0         101  Rahul    CSE     85          92            5                Yes
1         102  Priya    ECE     78          85            4                 No
2         103   Amit    CSE     92          78            7                Yes
3         104  Sneha     IT     67          65            2                 No
4         105  Rohan    CSE     88          90            6                Yes
5         106   Neha    ECE     76          88            4                Yes
6         107  Arjun     IT     95          96            8                Yes
7         108  Pooja    CSE     81          72            5                 No
8         109  Karan    ECE     72          80            3                 No
9         110  Meera     IT     89          94            6                Yes

In [ ]:
print(students.head())

   Student_ID   Name Branch  Marks  Attendance  Study_Hours Placement_Training
0         101  Rahul    CSE     85          92            5                Yes
1         102  Priya    ECE     78          85            4                 No
2         103   Amit    CSE     92          78            7                Yes
3         104  Sneha     IT     67          65            2                 No
4         105  Rohan    CSE     88          90            6                Yes

In [ ]:
students.shape

(10, 7)

In [ ]:
students.columns

Index(['Student_ID', 'Name', 'Branch', 'Marks', 'Attendance', 'Study_Hours',
       'Placement_Training'],
      dtype='object')

In [ ]:
#show students who have scored more than 80 marks

students[ students["Marks"] > 80 ]

   Student_ID   Name Branch  Marks  Attendance  Study_Hours Placement_Training
0         101  Rahul    CSE     85          92            5                Yes
2         103   Amit    CSE     92          78            7                Yes
4         105  Rohan    CSE     88          90            6                Yes
6         107  Arjun     IT     95          96            8                Yes
7         108  Pooja    CSE     81          72            5                 No
9         110  Meera     IT     89          94            6                Yes

In [ ]:
students["Marks"] > 80

0     True
1    False
2     True
3    False
4     True
5    False
6     True
7     True
8    False
9     True
Name: Marks, dtype: bool

In [ ]:
# Students who scored exactly 88

students[ students["Marks"] == 88]

   Student_ID   Name Branch  Marks  Attendance  Study_Hours Placement_Training
4         105  Rohan    CSE     88          90            6                Yes

In [ ]:
# Suppose we want the names and marks of students scoring above 85.

data = students[ students["Marks"] > 85]

In [ ]:
ans = data[["Name", "Marks"]]
ans

    Name  Marks
2   Amit     92
4  Rohan     88
6  Arjun     95
9  Meera     89

In [ ]:
students

   Student_ID   Name Branch  Marks  Attendance  Study_Hours Placement_Training
0         101  Rahul    CSE     85          92            5                Yes
1         102  Priya    ECE     78          85            4                 No
2         103   Amit    CSE     92          78            7                Yes
3         104  Sneha     IT     67          65            2                 No
4         105  Rohan    CSE     88          90            6                Yes
5         106   Neha    ECE     76          88            4                Yes
6         107  Arjun     IT     95          96            8                Yes
7         108  Pooja    CSE     81          72            5                 No
8         109  Karan    ECE     72          80            3                 No
9         110  Meera     IT     89          94            6                Yes

In [ ]:
# Students with marks above 80 AND attendance above 85%

data = students[(students["Marks"] > 80) and (students["Attendance"] > 85)]
data

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
# Students with marks above 80 AND attendance above 85%

data = students[(students["Marks"] > 80) & (students["Attendance"] > 85)]
data

   Student_ID   Name Branch  Marks  Attendance  Study_Hours Placement_Training
0         101  Rahul    CSE     85          92            5                Yes
4         105  Rohan    CSE     88          90            6                Yes
6         107  Arjun     IT     95          96            8                Yes
9         110  Meera     IT     89          94            6                Yes

In [ ]:
# Students from CSE OR IT

students[ (students["Branch"] == "IT") | (students["Branch"] == "CSE") ]

   Student_ID   Name Branch  Marks  Attendance  Study_Hours Placement_Training
0         101  Rahul    CSE     85          92            5                Yes
2         103   Amit    CSE     92          78            7                Yes
3         104  Sneha     IT     67          65            2                 No
4         105  Rohan    CSE     88          90            6                Yes
6         107  Arjun     IT     95          96            8                Yes
7         108  Pooja    CSE     81          72            5                 No
9         110  Meera     IT     89          94            6                Yes

In [ ]:
# Exclude students from the ECE branch

students[ students["Branch"] != "ECE"]

   Student_ID   Name Branch  Marks  Attendance  Study_Hours Placement_Training
0         101  Rahul    CSE     85          92            5                Yes
2         103   Amit    CSE     92          78            7                Yes
3         104  Sneha     IT     67          65            2                 No
4         105  Rohan    CSE     88          90            6                Yes
6         107  Arjun     IT     95          96            8                Yes
7         108  Pooja    CSE     81          72            5                 No
9         110  Meera     IT     89          94            6                Yes

In [ ]:
# Students scoring between 75 and 90, inclusive


students[students["Marks"]>=75 & students["Marks"]<=90]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
 students[ (students["Marks"]>=75) & (students["Marks"]<=90)]

   Student_ID   Name Branch  Marks  Attendance  Study_Hours Placement_Training
0         101  Rahul    CSE     85          92            5                Yes
1         102  Priya    ECE     78          85            4                 No
4         105  Rohan    CSE     88          90            6                Yes
5         106   Neha    ECE     76          88            4                Yes
7         108  Pooja    CSE     81          72            5                 No
9         110  Meera     IT     89          94            6                Yes

In [ ]:
students[students["Marks"].between(75,90)]

   Student_ID   Name Branch  Marks  Attendance  Study_Hours Placement_Training
0         101  Rahul    CSE     85          92            5                Yes
1         102  Priya    ECE     78          85            4                 No
4         105  Rohan    CSE     88          90            6                Yes
5         106   Neha    ECE     76          88            4                Yes
7         108  Pooja    CSE     81          72            5                 No
9         110  Meera     IT     89          94            6                Yes

In [ ]:
students[students["Marks"].between(76,89)]

   Student_ID   Name Branch  Marks  Attendance  Study_Hours Placement_Training
0         101  Rahul    CSE     85          92            5                Yes
1         102  Priya    ECE     78          85            4                 No
4         105  Rohan    CSE     88          90            6                Yes
5         106   Neha    ECE     76          88            4                Yes
7         108  Pooja    CSE     81          72            5                 No
9         110  Meera     IT     89          94            6                Yes

In [ ]:
students

   Student_ID   Name Branch  Marks  Attendance  Study_Hours Placement_Training
0         101  Rahul    CSE     85          92            5                Yes
1         102  Priya    ECE     78          85            4                 No
2         103   Amit    CSE     92          78            7                Yes
3         104  Sneha     IT     67          65            2                 No
4         105  Rohan    CSE     88          90            6                Yes
5         106   Neha    ECE     76          88            4                Yes
6         107  Arjun     IT     95          96            8                Yes
7         108  Pooja    CSE     81          72            5                 No
8         109  Karan    ECE     72          80            3                 No
9         110  Meera     IT     89          94            6                Yes

In [ ]:
#students whose study hours are either 4, 5 or 6

In [ ]:
students[ students["Study_Hours"].between(4,6)]

   Student_ID   Name Branch  Marks  Attendance  Study_Hours Placement_Training
0         101  Rahul    CSE     85          92            5                Yes
1         102  Priya    ECE     78          85            4                 No
4         105  Rohan    CSE     88          90            6                Yes
5         106   Neha    ECE     76          88            4                Yes
7         108  Pooja    CSE     81          72            5                 No
9         110  Meera     IT     89          94            6                Yes

In [ ]:
#students whose study hours are either 4, 5 or 7

students[students["Study_Hours"].isin([4,5,7])]

   Student_ID   Name Branch  Marks  Attendance  Study_Hours Placement_Training
0         101  Rahul    CSE     85          92            5                Yes
1         102  Priya    ECE     78          85            4                 No
2         103   Amit    CSE     92          78            7                Yes
5         106   Neha    ECE     76          88            4                Yes
7         108  Pooja    CSE     81          72            5                 No

In [ ]:
products = pd.DataFrame({
    "Product": ["Laptop Pro", "Laptop Air", "Wireless Mouse",
                "Gaming Keyboard", "Laptop Stand"],
    "Price": [80000, 65000, 1200, 3500, 900]
})

print(products)

           Product  Price
0       Laptop Pro  80000
1       Laptop Air  65000
2   Wireless Mouse   1200
3  Gaming Keyboard   3500
4     Laptop Stand    900

In [ ]:
products["Product"].contains("Laptop")

AttributeError: 'Series' object has no attribute 'contains'

In [ ]:
products["Product"].str.contains("Laptop")

0     True
1     True
2    False
3    False
4     True
Name: Product, dtype: bool

In [ ]:
products["Product"].str.contains("laptop")

0    False
1    False
2    False
3    False
4    False
Name: Product, dtype: bool

In [ ]:
products[products["Product"].str.contains("laptop")]

Empty DataFrame
Columns: [Product, Price]
Index: []

In [ ]:
products[products["Product"].str.contains("laptop", case = False)]

        Product  Price
0    Laptop Pro  80000
1    Laptop Air  65000
4  Laptop Stand    900

In [ ]:
products[products["Product"].str.contains("laptop", case = False, na = False)]

        Product  Price
0    Laptop Pro  80000
1    Laptop Air  65000
4  Laptop Stand    900

In [ ]:
# Display only the names and marks of students scoring above 80

data = students[students["Marks"] > 80]

In [ ]:
data[["Name", "Marks"]]

    Name  Marks
0  Rahul     85
2   Amit     92
4  Rohan     88
6  Arjun     95
7  Pooja     81
9  Meera     89

In [ ]:
students.loc[students["Marks"] > 80, ["Name", "Marks"]]

    Name  Marks
0  Rahul     85
2   Amit     92
4  Rohan     88
6  Arjun     95
7  Pooja     81
9  Meera     89