<a href="https://colab.research.google.com/github/swasfish-code/python/blob/main/IITH_missing_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
employees = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104],
    "Department": ["IT", "HR", "Finance", "IT"],
    "Salary": [50000, 45000, 60000, 70000]
})

In [ ]:
employees

   Employee_ID Department  Salary
0          101         IT   50000
1          102         HR   45000
2          103    Finance   60000
3          104         IT   70000

In [ ]:
emp_id = employees["Employee_ID"]
emp_id

0    101
1    102
2    103
3    104
Name: Employee_ID, dtype: int64

In [ ]:
dept = employees["Department"]
dept

0         IT
1         HR
2    Finance
3         IT
Name: Department, dtype: object

In [ ]:
salary = employees["Salary"]
salary

0    50000
1    45000
2    60000
3    70000
Name: Salary, dtype: int64

In [ ]:
avg_salary = salary.mean()
avg_salary

np.float64(56250.0)

In [ ]:
mx_salary = salary.max()
mx_salary

70000

In [ ]:
mn_salary = salary.min()
mn_salary

45000

In [ ]:
df = employees[["Employee_ID", "Salary"]]
df

   Employee_ID  Salary
0          101   50000
1          102   45000
2          103   60000
3          104   70000

In [ ]:
students = pd.DataFrame({
    "Name": ["Amit", "Priya", "Rahul", "Sneha"],
    "Marks": [85, 78, 92, 70],
    "Branch": ["CSE", "ECE", "CSE", "IT"]
})

In [ ]:
# loc and iloc

In [ ]:
students.loc[0]

Name      Amit
Marks       85
Branch     CSE
Name: 0, dtype: object

In [ ]:
students.loc[1:3]

    Name  Marks Branch
1  Priya     78    ECE
2  Rahul     92    CSE
3  Sneha     70     IT

In [ ]:
students

    Name  Marks Branch
0   Amit     85    CSE
1  Priya     78    ECE
2  Rahul     92    CSE
3  Sneha     70     IT

In [ ]:
students.loc[:, 1:3]

TypeError: cannot do slice indexing on Index with these indexers [1] of type int

In [ ]:
students.loc[:,["Name", "Marks"]]

    Name  Marks
0   Amit     85
1  Priya     78
2  Rahul     92
3  Sneha     70

In [ ]:
# iloc --> on the basis of position

In [ ]:
students

    Name  Marks Branch
0   Amit     85    CSE
1  Priya     78    ECE
2  Rahul     92    CSE
3  Sneha     70     IT

In [ ]:
students.iloc[0]

Name      Amit
Marks       85
Branch     CSE
Name: 0, dtype: object

In [ ]:
students.iloc[1:2]

    Name  Marks Branch
1  Priya     78    ECE

In [ ]:
# loc --> end is inclusive
# iloc --> end is exclusive

In [ ]:
students.iloc[0,1]

np.int64(85)

In [ ]:
#first 3 rows and first 2 columns

students.iloc[0:3, 0:2]

    Name  Marks
0   Amit     85
1  Priya     78
2  Rahul     92

In [ ]:
students = pd.DataFrame({
    "Name": ["A", "B", "C", "D", "E", "F"],
    "Branch": ["CSE", "ECE", "CSE", "IT", "CSE", "ECE"]
})

In [ ]:
students

  Name Branch
0    A    CSE
1    B    ECE
2    C    CSE
3    D     IT
4    E    CSE
5    F    ECE

In [ ]:
#Write a code to count the number of students within each department.

In [ ]:
students["Branch"].count()

np.int64(6)

In [ ]:
students["Branch"].value_counts()

Branch
CSE    3
ECE    2
IT     1
Name: count, dtype: int64

In [ ]:
counts = {}
for branch in students['Branch']:
    if branch in counts:
        counts[branch] += 1
    else:
        counts[branch] = 1

print(counts)

{'CSE': 3, 'ECE': 2, 'IT': 1}

In [ ]:
students["Branch"].unique()

array(['CSE', 'ECE', 'IT'], dtype=object)

In [ ]:
len(students["Branch"].unique())

3

In [ ]:
students["Branch"].nunique()

3

In [ ]:
students

  Name Branch
0    A    CSE
1    B    ECE
2    C    CSE
3    D     IT
4    E    CSE
5    F    ECE

In [ ]:
students.sort_values("Branch")

  Name Branch
0    A    CSE
2    C    CSE
4    E    CSE
1    B    ECE
5    F    ECE
3    D     IT

In [ ]:
students.sort_values("Branch", ascending = False)

  Name Branch
3    D     IT
1    B    ECE
5    F    ECE
0    A    CSE
2    C    CSE
4    E    CSE

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
students = pd.DataFrame({ "Student_ID": [101, 102, 103, 104, 105, 106], "Name": ["Rahul", "Priya", "Amit", "Sneha", "Rohan", "Neha"], "Branch": ["CSE", "ECE", "CSE", "IT", "CSE", "ECE"], "Marks": [85, 78, np.nan, 72, 88, np.nan], "Attendance": [92, 88, 95, np.nan, 90, 86], "Study_Hours": [5, np.nan, 6, 4, np.nan, 7] })

In [ ]:
students

   Student_ID   Name Branch  Marks  Attendance  Study_Hours
0         101  Rahul    CSE   85.0        92.0          5.0
1         102  Priya    ECE   78.0        88.0          NaN
2         103   Amit    CSE    NaN        95.0          6.0
3         104  Sneha     IT   72.0         NaN          4.0
4         105  Rohan    CSE   88.0        90.0          NaN
5         106   Neha    ECE    NaN        86.0          7.0

In [ ]:
students.isnull()

   Student_ID   Name  Branch  Marks  Attendance  Study_Hours
0       False  False   False  False       False        False
1       False  False   False  False       False         True
2       False  False   False   True       False        False
3       False  False   False  False        True        False
4       False  False   False  False       False         True
5       False  False   False   True       False        False

In [ ]:
students.isna()

   Student_ID   Name  Branch  Marks  Attendance  Study_Hours
0       False  False   False  False       False        False
1       False  False   False  False       False         True
2       False  False   False   True       False        False
3       False  False   False  False        True        False
4       False  False   False  False       False         True
5       False  False   False   True       False        False

In [ ]:
students.isnull().sum()

Student_ID     0
Name           0
Branch         0
Marks          2
Attendance     1
Study_Hours    2
dtype: int64

In [ ]:
students.isnull().sum().sum()

np.int64(5)

In [ ]:
students.isnull().sum(axis = 1)

0    0
1    1
2    1
3    1
4    1
5    1
dtype: int64

In [ ]:
students.isnull().any(axis = 1)

0    False
1     True
2     True
3     True
4     True
5     True
dtype: bool

In [ ]:
students[students.isnull().any(axis = 1)]

   Student_ID   Name Branch  Marks  Attendance  Study_Hours
1         102  Priya    ECE   78.0        88.0          NaN
2         103   Amit    CSE    NaN        95.0          6.0
3         104  Sneha     IT   72.0         NaN          4.0
4         105  Rohan    CSE   88.0        90.0          NaN
5         106   Neha    ECE    NaN        86.0          7.0

In [ ]:
students["Marks"].fillna(50)

0    85.0
1    78.0
2    50.0
3    72.0
4    88.0
5    50.0
Name: Marks, dtype: float64

In [ ]:
avg_marks = students["Marks"].mean()
students["Marks"].fillna(avg_marks)

0    85.00
1    78.00
2    80.75
3    72.00
4    88.00
5    80.75
Name: Marks, dtype: float64